name: Sync to Hugging Face hub
on:
  push:
    branches:
      - '**'

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Add remote
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://industoai:$HF@huggingface.co/spaces/industoai/Deep-Panorama-Stitcher
      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://industoai:$HF@huggingface.co/spaces/industoai/Deep-Panorama-Stitcher ${{ github.ref }}:main
